#!/bin/bash

echo Setting up Hardware

# Setting up short cuts
export SLOTS=/sys/devices/bone_capemgr.7/slots
echo \ \  Setting SLOTS = $SLOTS
export PINS=/sys/kernel/debug/pinctrl/44e10800.pinmux/pins
echo \ \  Setting PINS = $PINS

echo \ 
echo \ \  Current caps
cat $SLOTS
echo \ \  Current pins
cat $PINS|grep 890
cat $PINS|grep 894
cat $PINS|grep 89c
cat $PINS|grep 898
cat $PINS|grep 834
cat $PINS|grep 830
cat $PINS|grep 824
cat $PINS|grep 828
cat $PINS|grep 83c
cat $PINS|grep 838
cat $PINS|grep 82c
cat $PINS|grep 88c


exit 1;
