#!/bin/bash

echo Setting up Hardware

# Setting up short cuts
export SLOTS=/sys/devices/bone_capemgr.7/slots
echo \ \  Setting SLOTS = $SLOTS
export PINS=/sys/kernel/debug/pinctrl/44e10800.pinmux/pins
echo \ \  Setting PINS = $PINS

echo \ 
echo \ \  Setting up cap
echo \ \ \ \  Current caps
cat $SLOTS
echo \ \ \ \  Current pins
cat $PINS|grep 890
cat $PINS|grep 894
cat $PINS|grep 89c
cat $PINS|grep 898
cat $PINS|grep 834
cat $PINS|grep 830
cat $PINS|grep 824
cat $PINS|grep 828
cat $PINS|grep 83c
cat $PINS|grep 838
cat $PINS|grep 82c
cat $PINS|grep 88c

echo \ 
echo \ \  Applying cap
cd /lib/firmware
echo SSC-GPIO > $SLOTS
echo \ \ \ \  Current caps
cat $SLOTS
echo \ \ \ \  Current pins
cat $PINS|grep 890
cat $PINS|grep 894
cat $PINS|grep 89c
cat $PINS|grep 898
cat $PINS|grep 834
cat $PINS|grep 830
cat $PINS|grep 824
cat $PINS|grep 828
cat $PINS|grep 83c
cat $PINS|grep 838
cat $PINS|grep 82c
cat $PINS|grep 88c

echo \ 
echo \ \  Changing to Outputs
cd /sys/class/gpio/
echo 66 > export
echo "out" > gpio66/direction
echo 67 > export
echo "out" > gpio67/direction
echo 69 > export
echo "out" > gpio69/direction
echo 68 > export
echo "out" > gpio68/direction
echo 45 > export
echo "out" > gpio45/direction
echo 44 > export
echo "out" > gpio44/direction
echo 23 > export
echo "out" > gpio23/direction
echo 26 > export
echo "out" > gpio26/direction
echo 47 > export
echo "out" > gpio47/direction
echo 46 > export
echo "out" > gpio46/direction
echo 27 > export
echo "out" > gpio27/direction
echo 65 > export
echo "out" > gpio65/direction
